//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobile.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CHITIETDONDATHANGs = new HashSet<CHITIETDONDATHANG>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETSANPHAMs = new HashSet<CHITIETSANPHAM>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }


        public int MaSP { get; set; }

        [DisplayName("Tên nhà cung cấp")]
        public Nullable<int> MaNCC { get; set; }

        [DisplayName("Tên nhà sản xuất")]
        public Nullable<int> MaNSX { get; set; }

        public Nullable<int> MaLSP { get; set; }

        [DisplayName("Tên sản phẩm")]
        public string TenSP { get; set; }

        [DisplayName("Đơn giá")]
        public Nullable<decimal> DonGia { get; set; }

        [DisplayName("Ngày cập nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [DisplayName("Mô tả")]
        public string MoTa { get; set; }

        [DisplayName("Hình chính")]
        public string HinhChinh { get; set; }

        [DisplayName("Hình 1")]
        public string Hinh1 { get; set; }

        [DisplayName("Hình 2")]
        public string Hinh2 { get; set; }

        [DisplayName("Hình 3")]
        public string Hinh3 { get; set; }

        [DisplayName("Số lượng bán")]
        public Nullable<int> SoLuongBan { get; set; }

        [DisplayName("Số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }

        [DisplayName("Lượt xem")]
        public Nullable<int> LuotXem { get; set; }

        [DisplayName("Lượt bình chọn")]
        public Nullable<int> LuotBinhChon { get; set; }

        [DisplayName("Lượt bình luận")]
        public string LuotBinhLuan { get; set; }

        [DisplayName("Mới")]
        public Nullable<int> Moi { get; set; }

        [DisplayName("Đã xóa")]
        public Nullable<bool> DaXoa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAM> CHITIETSANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
